# 异常
## 概述
+ 异常指的是程序在运行过程中出现了问题，导致程序无法正常的运行下去，比如除零操作，内存泄漏，内存溢出等。

## 异常处理
+ C++ 异常是对程序运行过程中发生的异常情况的一种响应。异常提供了将控制权从程序的一部分传递到另一部分的部分
+ 对异常处理通常有三个组成部分：引发异常，使用处理程序捕获异常，使用 try 块
+ 引发异常：
    - throw 关键字表示引发异常，紧随其后的值指出了异常的特征
    - throw 语句本质是跳转，即命令程序跳到另一条语句。
    - 执行 throw 语句类似于执行返回语句，因为它也将终止函数的执行；但是 throw 不是将控制权返回给调用程序，而是导致程序沿函数调用序列后退，直至找到 try 块函数
+ 使用处理程序捕获异常
    - 程序使用异常处理程序（exception handler）来捕获异常，异常处理程序位于处理问题的程序中，catch 关键字表示捕获异常。
    - 处理程序以关键字 catch 开头，随后是位于括号中的类型声明，它指出了异常处理程序要响应的异常类型；
    - catch 关键字是异常类型用作标签，指出当异常被引发时，程序应该跳到这个位置执行
+ 使用 try 块
    - try 块标识其中特定的异常可能被激活的代码块，它后面跟着一个或多个 catch 块；
    - try 块是由关键字 try 指示的，关键字 try 的后面是一个由花括号括起来的代码块，表明需要这些代码引起的异常；

## 异常默认处理方式
+ 如果函数引发了异常，而没有 try 块或者没有匹配的处理程序时，将会调用 abort() 函数

+ 通常，引发异常的函数将传递一个对象。这样做有以下优点：
    - 可以使用不同的异常类型区分不同的函数在不同情况下引发的异常
    - 对象可以携带信息，程序可以根据这些信息来确定引发异常的原因，catch 块可以根据这些信息来决定采取什么样的措施

## 代码示例
+ 除 0 错误的异常捕获，不会导致程序崩溃

```
#include<iostream>
using namespace std;

int main()
{
    int dividend = 100;
    int divisor = 0;
    int quotient;

    try
    {
        if(divisor == 0) {
            throw "Division by zero conditional";
        }
        quotient = dividend / divisor;
        cout << "Quotient = " << quotient << endl;
    }
    catch(const char* msg){
        cout  << msg << endl;
    }

    return 0;   
    
}
```

[C++ 异常处理](https://zhuanlan.zhihu.com/p/508803947)